### ISSUE TITLE
non-translateable string

### ISSUE THREAD

**Issue by Duke-M-commits** [ReactiveDrop/reactivedrop_translations#1120]
can this one be made translateable? 
it's shown to the player pretty often and is translateable in the lobby
![image](https://github.com/ReactiveDrop/reactivedrop_translations/assets/69652463/47f06630-d18a-4606-a6ed-22faf45fea2c)

**Comment by Blueberryy** [comment]
How did you view that? I couldn't see that with default user settings

**Comment by Duke-M-commits** [comment]
just run a bit forward in the map

**Comment by BenLubar** [comment]
Do you have an addon that replaces the HUD? It's translated on my copy of the game.

**Comment by Duke-M-commits** [comment]
Yes, I had. But i disabled it, alongside all other mods + steam file validation. Same result.
![image](https://github.com/ReactiveDrop/reactivedrop_translations/assets/69652463/629a886e-b47b-48a9-a978-c13989915d4d) with grain

**Comment by Blueberryy** [comment]
![image](https://github.com/ReactiveDrop/reactivedrop_translations/assets/36592509/a384cd71-323e-4ca5-ba10-8d91abddfabd)
weird, it looks fine to me

**Comment by Duke-M-commits** [comment]
I just found out it works when the Steam ui is set to russian too.
@Blueberryy please try it with your Steam's ui set to english and ingame to russian.

**Comment by BenLubar** [comment]
> I just found out it works when the Steam ui is set to russian too. @Blueberryy please try it with your Steam's ui set to english and ingame to russian.

Does it still happen on beta for you? I tested with just the game language changed.

**Comment by Duke-M-commits** [comment]
Yes, same result in beta.
If Steams ui is the same as the ingame language it works, when set differently, it doesn't.

**Comment by Blueberryy** [comment]
> I just found out it works when the Steam ui is set to russian too. @Blueberryy please try it with your Steam's ui set to english and ingame to russian.

i guess it's inside source engine... just as in Left 4 Dead 2 that has font that can't be changed unless you change steam language to English.
I think it's impossible to fix right now until Ben get access to source engine in future. 😄

**Comment by BenLubar** [comment]
If you run the console command that reloads your HUD does it fix it?

I think what might be happening is that it's loading the translation before the game uses its custom translation loading code that handles longer strings properly.

**Comment by Duke-M-commits** [comment]
Can't reproduce that one anymore. It works, independent of steam- or game-language.
