### ISSUE TITLE
Text too long may overflow out of the hud or fail to display the rest of the over-the-limit characters

### ISSUE THREAD

**Issue by DucDuyGaming** [ReactiveDrop/reactivedrop_translations#1121]
I don't entirely sure if this belong in this repository or the [public source one](https://github.com/ReactiveDrop/reactivedrop_public_src). If this is the wrong place, I will move it there

In some of the Vietnamese translations I provided, it appeared to be a bit too long than some of the HUD and the interface allow. Thus, the text may appear to overflow out of some non-expandable HUD, or the "over-the-limit" characters will not display

While I can shorten these text myself, or in the case of the credit, split the line, I want to bring up this issue. In most cases, I don't feel like creating another PR just to thin down the text, nor do I want to hunt around the entire game for the issue. Plus, I have no idea if it is too long until I summit it and the beta version get updated, because I did not get a warning for such thing (unless I manually edit the text file myself in the game file for testing purpose)

Here is some of the examples that I found:
![20230927183414_1](https://github.com/ReactiveDrop/reactivedrop_translations/assets/117811607/8cdbfc75-53c3-4165-9c29-3792471c180a)
The previous Vietnamese text for "Enhanced Target Imaging" from the Marksman Rifle (and the first one that I found out). I removed the "nâng cao" part (Enhanced) in the lastest PR I made as of writing before discovering more other text that have the same issue

![20230927185220_1](https://github.com/ReactiveDrop/reactivedrop_translations/assets/117811607/dc8a61e7-48cf-4764-8e83-ce605cf2d30a)
This is hard to see, but the translation for "Ammo:" is a bit too long that it overflow the non-expandable part of the HUD

![20230930124755_1](https://github.com/ReactiveDrop/reactivedrop_translations/assets/117811607/28e241bf-5bcf-4c02-aa95-81c4b7e3e685)
The last part of the credit for Accident 32, the last few words fail to display
![20230930125335_1](https://github.com/ReactiveDrop/reactivedrop_translations/assets/117811607/7ba7a7b9-f22a-4281-97d3-b0006311364c)
![20230930125352_1](https://github.com/ReactiveDrop/reactivedrop_translations/assets/117811607/3219e84b-f345-4c11-bd2a-be79b679e34b)
Same issue for the note "Wide Spread, Slow Movement" and "Activatable Fire Rate Bonus" for Minigun and Heavy Rifle, respectively. Also, as shown, the box clearly show a lot of space, which both the alternate fire and note text can use

These are some of the related issue that I discovered, although the issue could also exist outside these shown areas. Unless I was given a "No" or it is not possible to resolve (in which case I'll probably just deal with it shorten the text, maybe), please have a look into this

**Comment by Duke-M-commits** [comment]
https://github.com/ReactiveDrop/reactivedrop_translations/discussions/497

**Comment by BenLubar** [comment]
For the credits one, you need to manually split the line into two lines in the credits file.

For the rest, I definitely need to work on those in the UI revamp I'm currently doing.

Still need to figure out how I want to get the new settings screen to fit longer descriptions better.
