### ISSUE TITLE
make translation-sync-tool.exe automatically remove spaces before string if it has translation

### ISSUE THREAD

**Issue by Blueberryy** [ReactiveDrop/reactivedrop_translations#1215]
would be handy if you translate big files and don't want to double click and backspace each space for every string

**Comment by BenLubar** [comment]
If you're using pretty much any modern text editor you can highlight multiple lines and press shift+tab to un-indent one level. The reason the translation sync tool doesn't do that is that we have four states:

- indented+same as english - untranslated
- indented+different from english - fuzzy translation (needs checking)
- unindented+same as english - translator has verified that the same sequence of letters works the same in both languages
- unindented+different from english - translation is complete

**Comment by Blueberryy** [comment]
> If you're using pretty much any modern text editor you can highlight multiple lines and press shift+tab to un-indent one level. The reason the translation sync tool doesn't do that is that we have four states:
> 
> - indented+same as english - untranslated
> - indented+different from english - fuzzy translation (needs checking)
> - unindented+same as english - translator has verified that the same sequence of letters works the same in both languages
> - unindented+different from english - translation is complete

Understadable. Thanks for info
