### ISSUE TITLE
[bug] translation-sync-tool not detecting correctly some brazilian translations

### ISSUE THREAD

**Issue by FurtadoPires** [ReactiveDrop/reactivedrop_translations#1492]
I'm working in update some new game texts to Brazilian Portuguese, and notice that the tool is detecting some of the files as "0% translate" despite already having translated lines in it.

**Comment by Duke-M-commits** [comment]
Did you remove both tabstops, on the english and the translated lines?

**Comment by FurtadoPires** [comment]
> Did you remove both tabstops, on the english and the translated lines?

That's probably it then, there's some time since I modified those files and didn't remember I had to do that.

Thank you @Duke-M-commits
