### ISSUE TITLE
Brazilian portuguese translation

### ISSUE THREAD

**Issue by FurtadoPires** [ReactiveDrop/reactivedrop_translations#15]
I'm intended to work in translating the game files  to Brazilian Portuguese language (commonly know as PT-BR)

Steam already makes distinction between portuguese and brazilian portuguese (it's called "brazilian" in translation files) and I will work with the files following this name pattern.

While the game already have portuguese translation, I would rather not touching it due to the fact that, while it's the same understandable language there are some words that are odd to one another.

@BenLubar once the files are done, could this translation be used as default for brazilian portuguese on steam? If so, which process should I do besides the MR?

---

- [x] `resource/basemodui_brazilian.txt`
- [x] `resource/gameui_brazilian.txt`
- [x] `resource/valve_brazilian.txt`
- [x] `resource/reactivedrop_brazilian.txt`
- [x] `resource/closecaption_brazilian.txt`
- [x] `resource/chat_brazilian.txt`
- [x] `rich_presence/563560_loc_brazilian.vdf` (create)
- [x] `store_page/store_brazilian.txt` (create)
- [x] `community/statsweb_brazilian.vdf`
- [x] `community/workshop_description_brazilian.txt` (create)
- [x] `community/workshop_tags_brazilian.json` (create)
- [x] `resource/mail/*_brazilian.txt` (create)
- [x] `resource/news/*_brazilian.txt` (create)
- [x] `community/item-schema.json`
- [x] `community/points_shop_brazilian.vdf`

**Comment by FurtadoPires** [comment]
Very nice, I would also like to use this issue to ask questions that may appear during the process, since I want to keep the terms as consistent as possible to the english version. Is it ok?

**Comment by BenLubar** [comment]
Yep, that's fine.

The files for you to edit are (and there's a lot of them, so this will take a while):

- [ ] `resource/basemodui_brazilian.txt`
- [ ] `resource/gameui_brazilian.txt`
- [ ] `resource/valve_brazilian.txt`
- [ ] `resource/reactivedrop_brazilian.txt`
- [ ] `resource/closecaption_brazilian.txt`
- [ ] `resource/chat_brazilian.txt`
- [ ] `rich_presence/563560_loc_brazilian.vdf` (create)
- [ ] `store_page/store_brazilian.txt` (create)
- [ ] `community/statsweb_brazilian.vdf`
- [ ] `community/workshop_description_brazilian.txt` (create)
- [ ] `community/workshop_tags_brazilian.json` (create)
- [ ] `resource/mail/*_brazilian.txt` (create)
- [ ] `resource/news/*_brazilian.txt` (create)
- [ ] `community/item-schema.json`
- [ ] `community/points_shop_brazilian.vdf`

(roughly in order of importance)

**Comment by FurtadoPires** [comment]
@BenLubar I've notice that a lot of lines from `resource/basemodui_` seems to de reminiscent from Xbox Live components and Left 4 Dead leftovers, is it necessary to translate everything or there's a specific session that's used in Alien Swarm?

**Comment by Blueberryy** [comment]
> @BenLubar I've notice that a lot of lines from `resource/basemodui_` seems to de reminiscent from Xbox Live components and Left 4 Dead leftovers, is it necessary to translate everything or there's a specific session that's used in Alien Swarm?

Most of the strings inside **resource/basemodui_** file are used in-game. You will have to translate it whole i guess :/

**Comment by FurtadoPires** [comment]
> 
> Most of the strings inside **resource/basemodui_** file are used in-game. You will have to translate it whole i guess :/

I will translate everything to make sure, but in the future I suggest that might be worth the effort to clean this file from unused parameters, in order to make maintenance easier and help in possible future new translations :)

An example of leftover parameters:
`"L4D360UI_Boomer"					"Boomer"
"L4D360UI_Hunter"					"Hunter"
"L4D360UI_Smoker"					"Smoker"
` 



> Heya! I can assist with proofreading and editing once the base translation is done. I actually proofread the original when it was on STS, it's a shame it was never shipped.

Thanks for the help @Tarkoviski, once I MR the files back, any help with revision will be welcome

**Comment by FurtadoPires** [comment]
Currently translating `resource/reactivedrop_brazilian.txt`

What's the meaning of ROSTER in game context?

**Comment by BenLubar** [comment]
`asw_roster` does not appear to be used. My best guess is that it was either some kind of unlock system for marines or part of the campaign wounding system that was cut during the development of the 2010 game.

**Comment by FurtadoPires** [comment]
@BenLubar I'm not sure what should I do with `community/item-schema.json`

It seems to be an unique file (not separated by language like the others), won't my modifications impact for other languages too?

**Comment by BenLubar** [comment]
For each line that has `_english` and needs translating (eg. isn't blank), copy it and make `_brazilian`. Since b comes before e, the `_brazilian` line should go above the `_english` line.

https://github.com/ReactiveDrop/reactivedrop_translations#item-schema

**Comment by FurtadoPires** [comment]
> For each line that has `_english` and needs translating (eg. isn't blank), copy it and make `_brazilian`. Since b comes before e, the `_brazilian` line should go above the `_english` line.
> 
> https://github.com/ReactiveDrop/reactivedrop_translations#item-schema

Now I've notice that I had an old version of this file, which was missing the language parameters.

**Comment by FurtadoPires** [comment]
There's also an typo in the original file

![image](https://user-images.githubusercontent.com/7890832/174497761-dbf4e6fb-5674-48c3-88ba-e53086571c02.png)

Line 80 is the same as line 75

**Comment by BenLubar** [comment]
Thanks, I've removed the duplicate.

**Comment by FurtadoPires** [comment]
Almost all files translated, now it's only missing the big one.

@BenLubar I've noticed that you made an `resource/reactivedrop_brazilian.txt` file that's a little different from the original `resource/reactivedrop_english.txt`

Should I work in this file or I can follow the the original layout?

**Comment by BenLubar** [comment]
You should work in `resource/reactivedrop_brazilian.txt`, since that's what the sync tool is assuming the input file will look like.

**Comment by BenLubar** [comment]
I've added Brazilian Portuguese as an option. If you don't see it, you can restart Steam to force it to update app information.

https://steamdb.info/app/563560/history/?changeid=15425452

**Comment by FurtadoPires** [comment]
I've managed to make it work, but that's a lot of `
Conditional Error: Bad expression token: ` errors.
would you know what the cause? Game is UTF-8 right?

**Comment by BenLubar** [comment]
If it works despite the error messages, then it's fine. The game files use UTF-16LE, but one of the two ways that localization files get loaded also supports UTF-8. It's transformed to UTF-16 by the build script.

**Comment by FurtadoPires** [comment]
> If it works despite the error messages, then it's fine. The game files use UTF-16LE, but one of the two ways that localization files get loaded also supports UTF-8. It's transformed to UTF-16 by the build script.

It only working partially, apparently game can't load my `reactivedrop_brazilian.txt` file, any way I can debug it? Might be some broken parameter since everything I wrote is UTF-8

**Comment by BenLubar** [comment]
If you send it to me, I can help you find it using regular expressions. My guess (based on what other people have had happen in the past) is that there's a missing or extra quotation mark somewhere.

**Comment by FurtadoPires** [comment]
An example of my current file [reactivedrop_brazilian.txt](https://github.com/ReactiveDrop/reactivedrop_translations/files/9116784/reactivedrop_brazilian.txt)

**Comment by BenLubar** [comment]
Lines 1506, 2978, and 4944 are missing one quotation mark each.

**Comment by FurtadoPires** [comment]
Thanks, that did the trick

How did you found those line? I think I might have other files with the same problem

**Comment by BenLubar** [comment]
The regular expression I wrote is

```
^(?!^\s*"[^"\\]*"\t\t"([^"\\]|\\["n\\])*"$).*$
```

**Comment by FurtadoPires** [comment]
Not sure how

> The regular expression I wrote is
> 
> ```
> ^(?!^\s*"[^"\\]*"\t\t"([^"\\]|\\["n\\])*"$).*$
> ```

Could you teach me how to do it if it isn't a problem?

**Comment by BenLubar** [comment]
There's a guide on how to use regular expressions on the wiki:

https://github.com/ReactiveDrop/reactivedrop_translations/wiki/How-to-translate-using-vscode#search-and-replace-using-regular-expressions

**Comment by FurtadoPires** [comment]
So far, I think I'm almost ready to release the first version

There are only some problems that I couldn't figure out what's the cause:
```
ILocalize::AddFile() failed to load file "Resource/valve_brazilian.txt".
```
```

KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file c:\program files (x86)\steam\steamapps\common\alien swarm reactive drop\reactivedrop\resource\closecaption_brazilian.txt
lang, Tokens, 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file c:\program files (x86)\steam\steamapps\common\alien swarm reactive drop\reactivedrop\resource\closecaption_brazilian.txt
lang, (*Tokens*), 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file c:\program files (x86)\steam\steamapps\common\alien swarm reactive drop\reactivedrop\resource\closecaption_brazilian.txt
lang, Tokens, 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file c:\program files (x86)\steam\steamapps\common\alien swarm reactive drop\reactivedrop\resource\closecaption_brazilian.txt
lang, (*Tokens*), 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file c:\program files (x86)\steam\steamapps\common\alien swarm reactive drop\reactivedrop\resource\closecaption_brazilian.txt
lang, Tokens, 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file c:\program files (x86)\steam\steamapps\common\alien swarm reactive drop\reactivedrop\resource\closecaption_brazilian.txt
lang, (*Tokens*), 
Failed to init 'maps/soundcache/_master_brazilian.cache'
Failed to init 'maps/soundcache/_master_brazilian.cache'
```
And of course, I think there's something wrong in this image :p
![20220714221629_1](https://user-images.githubusercontent.com/7890832/179160360-fb483cd4-a671-4fe4-b714-f2d898dfebc5.jpg)

Those are my current problematic files 
[reactivedrop_brazilian.txt](https://github.com/ReactiveDrop/reactivedrop_translations/files/9118240/reactivedrop_brazilian.txt)
[valve_brazilian.txt](https://github.com/ReactiveDrop/reactivedrop_translations/files/9118242/valve_brazilian.txt)

**Comment by BenLubar** [comment]
The mission completion screen needs to be manually updated for new letters, but that's my job: https://github.com/ReactiveDrop/reactivedrop_public_src/blob/reactivedrop_public/src/game/client/swarm/vgui/asw_scalable_text.cpp#L197

`Failed to init 'maps/soundcache/_master_brazilian.cache'` is safe to ignore - it means there's no translated version of the sound cache, which is correct because we don't have any translated sounds, so having separate sound caches for different languages would just waste disk space.

The error message mentions `closecaption_brazilian.txt`, so I'd check that for mismatched quotes in there.

**Comment by FurtadoPires** [comment]
> The mission completion screen needs to be manually updated for new letters, but that's my job
> 
I can also change my text to not include punctuation if  that's the only problem, I only need to know which parameter is that one

> The error message mentions `closecaption_brazilian.txt`, so I'd check that for mismatched quotes in there.

Now I've notice that you've updated this file to include the `[english]` tags, but in the meantime I've translated based on the `closecaption_english.txt `

Would be feasible to include those tags in my file? It'll be a lot of work to translate everything again :/

my current [closecaption_brazilian.txt](https://github.com/ReactiveDrop/reactivedrop_translations/files/9121958/closecaption_brazilian.txt)

**Comment by BenLubar** [comment]
copy your changes somewhere else as a backup (or commit them) and try running `translation-sync-tool.exe` in the utils folder. it should add the `[english]` lines, but it will also indent all of the strings it does that to, so you'll have to delete the indentation after.

**Comment by FurtadoPires** [comment]
```
   brazilian: panic: expected language name to match filename

goroutine 1 [running]:
main.updateLanguageFile(0x4d1808?, {0x4ae197?, 0x4aac1c?}, {0x4ab0d9, 0x9}, {0x4aa50e?, 0x1?})
        C:/Users/Owner/Documents/GitHub/reactivedrop_translations/utils/update_translations.go:353 +0x6ae
main.syncTranslations({0x4ae197, 0x15}, {0x4aa50e, 0x4}, 0x0)
        C:/Users/Owner/Documents/GitHub/reactivedrop_translations/utils/update_translations.go:125 +0x2b9
main.main()
        C:/Users/Owner/Documents/GitHub/reactivedrop_translations/utils/update_translations.go:76 +0x92
```

I tried to run in my branch without success, should I follow this path ` C:/Users/Owner/Documents/GitHub/reactivedrop_translations/utils/` to make it work?

**Comment by BenLubar** [comment]
If it's the same as https://github.com/FurtadoPires/reactivedrop_translations/runs/7348525048?check_suite_focus=true#step:4:84

the translation sync tool wants https://github.com/FurtadoPires/reactivedrop_translations/blob/master/resource/chat_brazilian.txt#L3 to be `"Language" "brazilian"`

**Comment by BenLubar** [comment]
It says 0% because when it added the `[english]` lines, it also indented everything to mark it as needing to be checked by a translator. if you run it again once the indentation is removed, it should say the correct percentage.

**Comment by BenLubar** [comment]
If the files are UTF-8 those error messages are expected and ignorable. (The game engine loads them, and then AS:RD loads them again with more features, such as the ability to have multiple addons contribute to the same file.)

At some point I want to get rid of compiled closecaption files - they made sense in Source Engine games where the server did not have access to the game's assets, but AS:RD is free and the compile doesn't really give us anything (they let the server send 4 byte IDs for closed captions instead of full variable-length strings, but we can compute those 4-byte IDs at runtime fairly cheaply).

**Comment by BenLubar** [comment]
Once you get it to a point where the sync tool is no longer making changes, send in a PR and let's get your files in the game.

**Comment by FurtadoPires** [comment]
> At some point I want to get rid of compiled closecaption files - they made sense in Source Engine games where the server did not have access to the game's assets, but AS:RD is free and the compile doesn't really give us anything (they let the server send 4 byte IDs for closed captions instead of full variable-length strings, but we can compute those 4-byte IDs at runtime fairly cheaply).

So once I PR my files, captions will work? It's a separated process related to those dat files?




> Once you get it to a point where the sync tool is no longer making changes, send in a PR and let's get your files in the game.

I'll make some more tests, but I think I'm good to send it today, should I squash my commits?

**Comment by BenLubar** [comment]
The closed caption compiler runs as part of the build script.

It's up to you whether you want to squash your commits. Some translators do, others don't.

**Comment by FurtadoPires** [comment]
Send my PR to approval #159
