### ISSUE TITLE
(Swedish) Updating Steam inventory names doesnt change it on Steam?

### ISSUE THREAD

**Issue by Crazymanbos** [ReactiveDrop/reactivedrop_translations#1618]
When I updated the name of the mapping medals, to the name they are supposed to have in the Swedish branch, they dont update on Steam? Its been like a month now? Is it Steams fault, or something else that causes it not to update?

**Comment by BenLubar** [comment]
I may have forgotten to upload the rendered json files. Oops! Thanks for letting me know.
