### ISSUE TITLE
Close Contact schinese mission name

### ISSUE THREAD

**Issue by BenLubar** [ReactiveDrop/reactivedrop_translations#229]
From the forums: https://steamcommunity.com/app/563560/discussions/2/3458220484827923043/

> # A Chinese translation problem
> A map express achievement called "deep contact" has become intimate contact, which should be changed to the word "in-depth"。The word "亲密" should be replaced by the word "深入"。

**Comment by zhongqingsong** [comment]
#230 
This issue has now been fixed.
