### ISSUE TITLE
[Text miss] Some EN strings are not in localization files

### ISSUE THREAD

**Issue by zhongqingsong** [ReactiveDrop/reactivedrop_translations#247]
When I played the game, I noticed that part of the text didn't have a translation for it. And some suggestions for the presentation of the text.
- [x] **Miss text**: Connection failed after 10 retries
- [x] **Miss text**: Generator Damage 
( Map : Illyn Forest, below picture)
- [x] Interesting phenomenon (a **minor bug**, perhaps)
after finish "Bring the reactor online" (Map Rydberg Reactor), Cmr  will speak twice, the first to say object accomplished, and the second to say that the situation is not good ( closecaption_.txt -> **Command.co_m3_ob3**). The ob3 is very very very long text (It's also a long voice too, Maybe half a minute of Cmr voice? ).
And then the ob3, it's almost impossible to get to the end of the speech. As long as any new subtitle (alien attack, soldier attack, etc.) appears before the end of the speech. Ob3 subtitles will disappear automatically.
The bug I reported earlier is ReactiveDrop/reactivedrop_public_src#154.  Then the issue was closed and I found that the issue had not been changed anything. So, I deliberately to summarize and reproduce this problem.
( I guessed that the height of the subtitle is fixed. If the height of the subtitle bar is exceeded, the previous information will be automatically removed. )

![Snipaste_2022-08-20_13-10-32](https://user-images.githubusercontent.com/35858818/185730501-e7dae51a-5bb7-47e3-bae1-874b9a4b4216.png)

**Comment by Blueberryy** [comment]
Thank you for mentioning it up and forcing Ben to add disconnect message translatable

**Comment by BenLubar** [comment]
The good news is that we already had a translated message (it just wasn't used), so there's nothing new to translate.

**Comment by Blueberryy** [comment]
> The good news is that we already had a translated message (it just wasn't used), so there's nothing new to translate.

That was smart cat meowe and why only you developing this game so actively? Where's all other devs gone?

**Comment by BenLubar** [comment]
> Where's all other devs gone?

Dmitriy is busy with work and other real life stuff, Orange and jhheight are working on content, and Mithrand is working on behind-the-scenes stuff. Don't know what Dubstep and element109 are doing - probably their own personal projects or real life stuff.

**Comment by zhongqingsong** [comment]
Thanks, If you're making an Android game, I can help a little bit. PC development doesn't.
: )

**Comment by BenLubar** [comment]
Trust me, you're already helping a lot by translating and reporting bugs.

**Comment by BenLubar** [comment]
I believe the closed caption problem was related to the string truncation bug.
