### ISSUE TITLE
[bug] Mission end text lacks texture

### ISSUE THREAD

**Issue by zhongqingsong** [ReactiveDrop/reactivedrop_translations#250]
My previous submission changed the end of the assignment #246 . Now that I'm in the game, there's still no texture for text.
I guess you didn't see it, so, uh, I wanted to tell you.
The previous translation, which had symbols in it, didn't feel particularly good. So, in the new translated text, the use of symbols is removed.
In the new text, there are some complex characters. So, I needed to get into the game and actually experience the visual feel. If the text is bad, I might update the end text again. Thank you
These all texts are:
此场战役
本次任务
顺利完成
遗憾败北

![Snipaste_2022-08-17_21-28-43](https://user-images.githubusercontent.com/35858818/185148817-b2db6b3a-4ce6-4d83-89b3-6966a7169515.png)

**Comment by BenLubar** [comment]
I don't think I've released a beta update since that PR was merged. Here's an addon with the letters I made:

[add_letters.zip](https://github.com/ReactiveDrop/reactivedrop_translations/files/9365720/add_letters.zip)

**Comment by BenLubar** [comment]
The beta is updated. Are you still seeing the wood texture?

**Comment by zhongqingsong** [comment]
> The beta is updated. Are you still seeing the wood texture?

OK It's all right, The characters are now displayed. It looks good. 
: )
