### ISSUE TITLE
[advice] Comments on the document management of the current translation notes

### ISSUE THREAD

**Issue by zhongqingsong** [ReactiveDrop/reactivedrop_translations#375]
The current ".\release_notes" management is relatively simple and there are no problems at present. But, as might be expected, As the number of update logs increases, the files in the entire folder will increase if we continue with the current process.
Of course, it doesn't affect the translation. However, when there are too many files, it becomes inconvenient to view and select the specified files. Therefore, I have a small suggestion: make a change to the translation file of the update log for the convenience of subsequent maintenance.
**How to do**
I won't say much about the current file structure, but I'll give you one of my management methods (for reference only).  
As shown below:
![image](https://user-images.githubusercontent.com/35858818/190848891-5b1f6d9c-435f-48ec-ae83-a1d71c9590e1.png)
The whole structure is very simple, is through the folder to carry out the classification:
When you have an update date, create a new date folder and cut the corresponding NEXT into it. Then they become Old notes.
When you have a new NEXT file, or keep your current operating mode, create a new NEXT file, They become New notes, and we can see it very easily and then translate the new document.

**Comment by BenLubar** [comment]
I've moved already-published patch notes into a folder and left the NEXT (unknown date), 20230419 (anniversary experience bonus announcement), and 20230420 (anniversary new post draft) where they are currently.
