### ISSUE TITLE
'Hullen' in korean translation

### ISSUE THREAD

**Issue by DukeDukeEm** [ReactiveDrop/reactivedrop_translations#425]
@BRAIN-IS-BACK 
By chance I stubled upon a comment in the korean translation which says '// Original Hullen, probably referring to Helen.' (rd_res_rctinbound2_koreana.txt).
'Hullen' has been translate to 'Helen' in the korean translation. Which I think is wrong, Hullen is a person different from Helen Young.

**Comment by DukeDukeEm** [comment]
On second thought and a lookup I realized there are multiple strings like `asw_pda_owner_name__USERNAME_` in reactivedrop_LANGUAGE.txt
None of them belongs to Helen Young, which is mentioned multiple times in mails.
Maybe brain-is-back is right.
@BenLubar do you have any idea whom to ask about this?

**Comment by BRAIN-IS-BACK** [comment]
> Hullen

@DukeDukeEm 
Hullen to 'Helen' is the evil that I copied and emblazoned the sentence into the translator.
It happened because I didn't do a proper inspection.
I will change the contents right now and upload them together at the next translation upload.

**Or just fix that part right now.**

**Comment by BRAIN-IS-BACK** [comment]
> On second thought and a lookup I realized there are multiple strings like `asw_pda_owner_name__USERNAME_` in reactivedrop_LANGUAGE.txt None of them belongs to Helen Young, which is mentioned multiple times in mails (she owns 3 pdas in labsmail1, queenlairmail1 and queenlairmail2). Maybe brain-is-back is right. @BenLubar do you have any idea whom to ask about this?

@DukeDukeEm 

wait, what??
Is it correct that I translated it correctly?

**Comment by BRAIN-IS-BACK** [comment]
> rd_res_rctinbound2_koreana

@DukeDukeEm 

rd_res_rctinbound2_koreana?

I remember this file I didn't touch.

**Comment by DukeDukeEm** [comment]
I mean it's possible that this is an ages old typo.
@BenLubar where are these asw_pda_owner_name_USERNAME strings used?

**Comment by DukeDukeEm** [comment]
> > Hullen
> 
> @DukeDukeEm Hullen to 'Helen' is the evil that I copied and emblazoned the sentence into the translator. It happened because I didn't do a proper inspection. I will change the contents right now and upload them together at the next translation upload.
> 
> **Or just fix that part right now.**

Please wait with changes until we are sure what is what.

**Comment by BRAIN-IS-BACK** [comment]
> > > Hullen
> > 
> > 
> > @DukeDukeEm Hullen to 'Helen' is the evil that I copied and emblazoned the sentence into the translator. It happened because I didn't do a proper inspection. I will change the contents right now and upload them together at the next translation upload.
> > **Or just fix that part right now.**
> 
> Please wait with changes until we are sure what is what.

ok. i will wait for it.

**Comment by DukeDukeEm** [comment]
**Hullen** is hitting on **Jenny** (going out for dinner) in rd_res_rctinbound1, sounds like Hullen is a man.
There are 3 Helens:
- Helen Baker: is pretty new to the story, in the accident 32 campaign, so no relation
- Helen Moreau: same but nam humanum campaign 
- **Helen Young**: seems to be in love with Brian Howe (queenlairmail2)

So, now Hullen could be a lesbian, bug still, she would hit on Jenny while being in love with Brian (both mails, Hullen and Helens have the same date). I think these are 2 different characters.

**Comment by BRAIN-IS-BACK** [comment]
> **Hullen** is hitting on **Jenny** (going out for dinner) in rd_res_rctinbound1, sounds like Hullen is a man. There are 3 Helens:
> 
> * Helen Baker: is pretty new to the story, in the accident 32 campaign, so no relation
> * Helen Moreau: same but nam humanum campaign
> * **Helen Young**: is in love with Brian Howe (queenlairmail2)
> 
> So, now Hullen could be a lesbian, but still, she would hit on Jenny while being in love with Brian (both mails, Hullen and Helens have the same date). I think these are 2 different characters.

still, It may be so. But still, **BenLubar**'s explanation is needed.

**Comment by BenLubar** [comment]
These four characters with similar names are from different campaigns, based on the filenames.

**Comment by BRAIN-IS-BACK** [comment]
@BenLubar so, **Hullen vs Helen**. what is Right?

**Comment by BRAIN-IS-BACK** [comment]
> These four characters with similar names are from different campaigns, based on the filenames.

so, Hullen vs Helen. what is Right?

**Comment by DukeDukeEm** [comment]
Hullen

**Comment by BRAIN-IS-BACK** [comment]
> 

then, all Helen must be Hullen at once...

**Comment by BRAIN-IS-BACK** [comment]
> > so, Hullen vs Helen. what is Right?
> 
> Hullen

then, all Helen must be Hullen at once...

**Comment by BRAIN-IS-BACK** [comment]
> > so, Hullen vs Helen. what is Right?
> 
> Hullen

One of the reasons for Hullen's translation into Hellen seems to be because of annotations written by translators in the past.

**"The original is Hullen, but it seems to refer to Hellen."**

With this annotation, it seems that Hullen was translated as Hellen.
But now that this turns out to be wrong, I'll translate Hullen properly.

**Comment by DukeDukeEm** [comment]
Hullen is mentioned in 3 places:
* `asw_pda_owner_name_hullen` in reactivedrop_*.txt
* 4 times in rd_res_rctinbound1_*.txt
* 2 times in rd_res_rctinbound2_*.txt

**Comment by BRAIN-IS-BACK** [comment]
> Hullen is mentioned in 3 places:
> 
> * `asw_pda_owner_name_hullen` in reactivedrop_*.txt
> * 4 times in rd_res_rctinbound1_*.txt
> * 2 times in rd_res_rctinbound2_*.txt

i just PR it. thx.
