### ISSUE TITLE
Translating key bindings

### ISSUE THREAD

**Issue by DukeDukeEm** [ReactiveDrop/reactivedrop_translations#427]
How can I translate key bindings?

![image](https://user-images.githubusercontent.com/69652463/192338974-1be71861-6d42-47b3-8c06-d149d3e3ce09.png)

Also:
That screenshot is a good example for how the positioning of the text is a bit akward, it overlaps the icon and looks somehow too big (in comparison to the weapon name).

**Comment by BenLubar** [comment]
you *might* be able to do it with just `"MOUSE5"` - if not, I'll check what the code is actually doing

**Comment by BenLubar** [comment]
Double-checked, and it is indeed just the string that appears on-screen (case insensitive).

As of a recent beta, controller buttons no longer show up as text here, and a few other places where controller buttons may show up as text now use the Steam-provided translation for those buttons (which means we don't have to handle each controller's terminology separately).
