### ISSUE TITLE
Better progress.md

### ISSUE THREAD

**Issue by DukeDukeEm** [ReactiveDrop/reactivedrop_translations#520]
As of now the table in progress.md has some downsides:
* Table is cut off because of long contents per cell (the git webview is probably the most seen visual representation for that file)
* Percentages with 3 decimal places are a bit too detailed to be nice to read (the file is meant to be read by humans, it wont get reread by a machine)
* Fully translated languages are included in the table which rises the width further (but there isn't a breakdown information in these to be found by the reading person)

I sketched a shorter and easier to read document:
* shortened the language-columns (first 3 characters of language string) and added tooltips with full names on hover
* removed percentages in the whole (that's something for a nice comparison graph)
* removed fully translated language columns
* added a list of fully translated languages at the top
* removed non curated language columns
* added a list of non curated languages at the bottom
* linked files to their directories

I created a mockup [here](https://github.com/DukeDukeEm/rd_translation_german/blob/progress_sketch/PROGRESS.md)
How about that?
And why? I think a good representation of the progress could motivate new visitors to contribute.

Disclaimer: I can't write GO, so I can only provide my input, somebody else would have to change `update_translations.go`

Before:
![image](https://user-images.githubusercontent.com/69652463/199941140-1f111d9c-89f4-45a2-b9d3-b5cc2cc8c52d.png)
After:
![image](https://user-images.githubusercontent.com/69652463/199940947-8ab4fbf9-a649-416c-ab93-74f92830e6bc.png)

_Originally posted by @DukeDukeEm in https://github.com/ReactiveDrop/reactivedrop_translations/discussions/512_

**Comment by zhongqingsong** [comment]
This new style is great. But if there are more countries and regions, there will still be more than the boundaries of the page display. When that happens, it's even more troublesome. So, I adjusted the presentation of the whole data. It went from horizontal to vertical.
Like below (Data and language are arbitrary and do not represent progress results. It's only used for styling.):
![Snipaste_2022-11-09_23-18-38](https://user-images.githubusercontent.com/35858818/200870115-e7c6cff4-b331-4174-b30b-b6dae85c3e70.png)

In this way, there is no need to worry about new situations arising as more countries and regions grow. Of course, we need to trim some of the names of the files.

**Comment by BenLubar** [comment]
Does the grid actually help with readability, or would it be better to have one section per language with a summary of what's incomplete? If we do that, we can also add stuff like mail and link directly to files that need updating.

**Comment by zhongqingsong** [comment]
> Does the grid actually help with readability, or would it be better to have one section per language with a summary of what's incomplete? If we do that, we can also add stuff like mail and link directly to files that need updating.

I think Yes, first of all, the new md, whether it's Duke or my style, It looks neat, and you can see the data for each language at a glance. Second, it is very convenient to view the data. The old way of presenting data, especially in the last countries. They had to click on the scroll bar with their mouse and drag it manually. You have to reclick the scroll bar if you make a mistake. With the new data presentation, people just need to scroll the mouse wheel to see all the data, it's much easier!!

**Comment by Blueberryy** [comment]
What about icons for languages and file names?

**Comment by DukeDukeEm** [comment]
> What about icons for languages and file names?

There are no icons for languages, there are only flag-icons for countries, using flags for languages is troublesome.
As an example, I translate into german, this language is officially spoken in 3 countries, which ends in something like this:
![image](https://user-images.githubusercontent.com/69652463/201339570-6c309ac2-d584-4574-bc69-f6bd1061187f.png)
Another example could be the differentiation between schinese and tchinese.

Icons for files: I don't understand how this could not be just an repeated file icon. Please explain :)

**Comment by Blueberryy** [comment]
> > What about icons for languages and file names?
> 
> There are no icons for languages, there are only flag-icons for countries, using flags for languages is troublesome. As an example, I translate into german, this language is officially spoken in 3 countries, which ends in something like this: ![image](https://user-images.githubusercontent.com/69652463/201339570-6c309ac2-d584-4574-bc69-f6bd1061187f.png) Another example could be the differentiation between schinese and tchinese.
> 
> Icons for files: I don't understand how this could not be just an repeated file icon. Please explain :)

ah gotcha, well then i think it's all good to open pull request with your improvements

**Comment by DukeDukeEm** [comment]
No, my mockup is static, it can't update on it's own like the current md.

**Comment by DukeDukeEm** [comment]
> Does the grid actually help with readability, or would it be better to have one section per language with a summary of what's incomplete? If we do that, we can also add stuff like mail and link directly to files that need updating.

I do think we should see something which allows to compare all languages in one place. Having a section per language sounds like it would make the progress report much longer. And such it would defeat the purpose of motivating new users to contribute. So yes, it helps the readability by a lot ... for the right targetgroup. A longer report per language would be helpful for already contributing users, I do not think this should be the targetgroup, they can just search for double tabs in the beginning of the line and get what they need in the course of translating.

**Comment by DukeDukeEm** [comment]
> This new style is great. But if there are more countries and regions, there will still be more than the boundaries of the page display. When that happens, it's even more troublesome. So, I adjusted the presentation of the whole data. It went from horizontal to vertical. Like below (Data and language are arbitrary and do not represent progress results. It's only used for styling.): ![Snipaste_2022-11-09_23-18-38](https://user-images.githubusercontent.com/35858818/200870115-e7c6cff4-b331-4174-b30b-b6dae85c3e70.png)
> 
> In this way, there is no need to worry about new situations arising as more countries and regions grow. Of course, we need to trim some of the names of the files.

The list of different files/folders will certainly rise, the list of languages won't jump up so fast, we can think (eg. shorten the file-column somehow) about changing the layout with switched axis when the problem starts to really exist.

**Comment by zhongqingsong** [comment]
> 

Yes, there won't be many languages in a short time. But it's important to note that when you really need to switch between horizontal and vertical axes, it's not easy. The **md** is not **Excel**, it can not automatically convert horizontal and vertical axes, it needs to rewrite the code to adjust.

**Comment by DukeDukeEm** [comment]
Yes you can, as far as i know that's a mapped array out of which an markdown table is generated. Since I can't do that, I need to be careful how I promote the easieness of such a change, but it's certainly better to handle than an Excel sheet.

**Comment by BenLubar** [comment]
Right now, the markdown output (search https://github.com/ReactiveDrop/reactivedrop_translations/blob/e490cd130ad0af425fd43f51ef760daf5186e904/utils/update_translations.go for `flagMarkdown`) is just fancy log messages. Given how we've ended up using the sync tool with the CI bot, it's probably best to separate the progress.md generation from the actual sync process so it's less tightly coupled and we can do whatever formatting of the information makes the most sense.

**Comment by DukeDukeEm** [comment]
It's now more technically helpful for already working translators.
It lost all and any incentive for new visitors to do or see anything motivating which they could work on.
So you made it even more helpful and wholesome as it was ... into the opposite direction I proposed.
* the user has to scroll for long
* the user has to click very much
* the user has no comparision to what is done or missing

It deserves a new name, maybe 'progression helper'.

**Comment by BenLubar** [comment]
I've added a summary table to the top. How does that look?

**Comment by DukeDukeEm** [comment]
Wow, very good. Now it has everything at once, a well arranged first-glance comparison, all the details and the proposed axis.
I don't get the difference between the capitalized and non-capitalized column-headers. What does "Strings" include?

**Comment by BenLubar** [comment]
Non-capitalized headers are specific strings files, the Strings header is strings not included in one of the files that gets an individual header.

Inventory is the number of missing language-specific keys in the inventory schema, and Files is the number of files that are missing or contain indented lines.

**Comment by DukeDukeEm** [comment]
I am very very happy with the outcome of this issue. The progress report is now really helpful for everyone, thanks to everyone involved.
