### ISSUE TITLE
[discussion] New Chinese name

### ISSUE THREAD

**Issue by zhongqingsong** [ReactiveDrop/reactivedrop_translations#574]
The current Chinese name is not particularly fit. So, I recently thought of a better name, you can refer to, feel need to replace. New name is "虫启天降".
1. "虫启": It literally means Swarm priming, which means Swarm appearing. At the same time, it sounds like Chinese "重启". "重启" means restart, this corresponds to "Reactive".
2. "天降": It mean Fall from the sky. That corresponds to the paratroopers "Drop".

How do you feel about it? Do you want to use a new Chinese name?

**Comment by BenLubar** [comment]
So just to be clear, the full name is `异形丛生：虫启天降`?

I'll set it up and see if we get any feedback from players. Can always revert if they don't like it.

**Comment by ywgATustcbbs** [comment]
definately not a good idea to change the name now and then. The new name feels like it comes from a taiwan translator. At least i expect some translations relayed to the English word. The name should be consistent to the widely accepted community name.

**Comment by zhongqingsong** [comment]
> 



> So just to be clear, the full name is `异形丛生：虫启天降`?
> 
> I'll set it up and see if we get any feedback from players. Can always revert if they don't like it.
Yes, It's related to the name of the game you told me earlier. Do you want me to replace the PR directly, or do you want to update it and see the player feedback?

**Comment by zhongqingsong** [comment]
> definately not a good idea to change the name now and then. The new name feels like it comes from a taiwan translator. At least i expect some translations related to the English word. The name should be consistent to the widely accepted community name.

这个名称的话，你可以找找之前的帖子。这个英文的游戏名意思是，虫子突然出现了，然后伞兵降落。
所以，我感觉新名称挺符合的。至于你说的湾湾调，这个就见仁见智了。

**Comment by BenLubar** [comment]
The new name is now live everywhere except the files distributed with the game. (That is, only the beta branch currently has the previous name - the public/default branch is using translations from before the game's name was localized.)

**Comment by zhongqingsong** [comment]
The title has been explained in various places, including github and steam. I will raise the issue later if there are any questions. I will close this issue first.
