### ISSUE TITLE
fix inconsistencies in korean translation

### ISSUE THREAD

**Issue by 906bc906** [ReactiveDrop/reactivedrop_translations#68]
There are some inconsistencies in korean translation.

- Swarm
	- 에일리언
	- 외계무리
	- 외계 무리
- Parasite
	- 기생충
	- 감염충
- Swarm egg
	- 기생충 알
	- 에일리언 알
- Sentry gun
	- 센트리
	- 센트리 건
	- 포탑
- Xenomite
	- 제너마이트
	- 문어충
- IAF
	- IAF
	- 성간군사동맹
	- 동맹군
- Vereon XII
	- Vereon XII
	- 베레온 XII
	- 베레온XII
	- 베레온 제12 항성계

We should talk about this inconsistencies to resolve.
@BRAIN-IS-BACK, or any korean translator.

**Comment by BRAIN-IS-BACK** [comment]
oh..........
The above situation is a harmful effect caused by using a translator.

**Comment by BRAIN-IS-BACK** [comment]
I will unify most translations into one according to the above points
But some will leave it at that.

"If you’ve played Alien Swarm before,"

In the sentence above, Alien Swarm literally means the name of the game as it is pronounced.
The name of the game we are translating is Alien Swarm. So Alien Swarm will also change the Korean pronunciation to be Alien Swarm.

**Comment by 906bc906** [comment]
I agree with you.

I also understand what you said about 'Swarm'.

---

말씀하신 의견에 전적으로 동의합니다.

스웜에 대해 얘기하신 부분들도 무슨 뜻인지 이해했습니다. 말씀하신 것이 맞습니다.

이와 관련된 풀 리퀘스트 작성하실 때 이 이슈 멘션해주시면 풀 리퀘스트 확인하고 이슈 닫겠습니다. ( #68 이런 식으로요 )

아니면 직접 이슈 닫아주셔도 괜찮구요.

**Comment by BRAIN-IS-BACK** [comment]
#68?
깃헙 사용법을 잘 몰라서 "이 이슈 멘션" 이라는 게 무슨 뜻인지 모르겠어요.
I don't know what "이 이슈 멘션" means because I don't fully understand how to use git-hub.

But you can close this issue.
이 이슈 닫아도 되요.
#68#68#68#68#68

(어떻게 닫는지 몰라서 일단 #68 을 연발해 이 이슈는 닫아도 된다는 것을 알리고 있다)
(I don't know how to close it, so I'm sending #68 to let you know that it's okay to close this issue.)

**Comment by 906bc906** [comment]
@BRAIN-IS-BACK 

Unless there are any specific reasons, This issue shouldn't be closed until PR that resolves issue is merged. 

When you submit a PR about this issue, write '#68' in the title of the commit message or in the body of the PR. Then you'll see that the message '~mentioned this issue' appears at the bottom of this issue.


---

이 이슈는 번역 비일관성을 해결할 것을 요구하고 있습니다. 따라서 특별한 이유가 없다면 이 이슈를 해결하는 커밋이 마스터 브랜치에 적용되기 전까지는 닫아서는 안 됩니다.

이 이슈를 해결하는 풀 리퀘스트를 제출하실 때, 커밋 메세지의 제목이나 풀 리퀘스트의 본문에 '#68' 를 적어보세요. 그러면 이 이슈의 하단에 '~mentioned this issue' 이라는 메세지가 기재되고 어디서 언급했는지 확인할 수 있습니다.

이런 식으로 이슈를 언급하면, 이슈를 보는 사람은 어떤 PR 또는 커밋이 이 이슈를 해결했는지 쉽게 확인할 수 있고, PR을 관리하는 사람은 이 PR이 어떤 이슈를 해결하는지 확인할 수 있습니다.
