### ISSUE TITLE
EULA content seems to break iframes width

### ISSUE THREAD

**Issue by DukeDukeEm** [ReactiveDrop/reactivedrop_translations#841]
I'm not sure if this is even coming from the text we include there, maybe Valve messed something up on their own here.
![image](https://user-images.githubusercontent.com/69652463/234065288-072469da-9bd2-49cb-b5d6-cc962276382c.png)

Edit: Probably an Steam client issue itself.

Could be the additional padding in 'main'
![image](https://user-images.githubusercontent.com/69652463/234063604-6d718473-945e-4578-8824-57353c226861.png)

Or an fixed width in 'eula_main'
![image](https://user-images.githubusercontent.com/69652463/234065596-3050cf64-7da0-452a-ac88-7465801d95d5.png)

**Comment by BenLubar** [comment]
We don't have that level of control over the EULA's presentation (it's just bbcode) so this is definitely on Valve's end.

![image](https://user-images.githubusercontent.com/4257305/234123386-4d8b659d-05e7-4222-8a9e-d1ec95e3e13f.png)
